apiVersion: v2
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVNOM1FZQ1o1Tkw0RUdQSEwKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gYTBGNVVVbncwRkxTZFNWOEJGMWdtK3BLbFVOUTA5cGUvYkNnYlVPNQpbc2VydmVsZXNzdXNlcl0KYXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBU04zUVlDWjVOTDRFR1BITAphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBhMEY1VVVudzBGTFNkU1Y4QkYxZ20rcEtsVU5RMDlwZS9iQ2diVU81Cg==
